### ISSUE TITLE
Some scripts seem to be missing

### ISSUE THREAD

**Issue by Lyken17** [runlevel5/linuxbrew-ppc64le#1]
Thanks for sharing these useful scripts! However, some scripts mentioned in readme seem to be missing.

```
master/patches/linuxbrew-core/0001-support-ppc64le.patch
0001-update-makedepend-with-patched-version.patch 
```

Could you tell me where I can find them?

**Comment by runlevel5** [comment]
@Lyken17 let me get the code re-based

**Comment by Lyken17** [comment]
Thanks in advance!

**Comment by runlevel5** [comment]
@Lyken17 I am nearly there, the plan is to fork and maintain brew for ppc64le variant, I've created github.com/runlevel5/brew-ppc64le. It's not working yet FYI. I am sorting out the static linking issue with libc6 and musl libc. Once done, I will let you know

**Comment by runlevel5** [comment]
@Lyken17 FYI following up on this issue with upstream https://github.com/Homebrew/homebrew-portable-ruby/issues/98

**Comment by runlevel5** [comment]
@Lyken17 please give it a go at https://github.com/homebrew-ppc64le/install

So far I've only tested against Debian Buster. Feel free to submit any bug report there
